name: online_shopping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_vector_icons: ^2.0.0
  flutter_iconly: ^1.0.2 
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  dynamic_height_grid_view: ^0.0.3
  card_swiper: ^3.0.1
  fluttertoast: ^8.2.8
  ionicons: ^0.2.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6
  # firebase_storage: ^11.5.6
  # google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

assests:
  - assets/images/
  - assets/images/bag/
  - assets/images/banners/
  - assets/images/categories/  
  - assets/images/profile/
  - assets/images/bag/shopping_cart.png


